### ISSUE TITLE
Add option to generate dirty state hash of tracked files

### ISSUE THREAD

**Issue by aalexgabi** [tvdstaaij/node-git-describe#14]
This generates a unique id for for a given set of uncommitted changes in tracked files.
```
git diff | sha1sum | head -c 7
```
Here is an npm script that illustrates the idea behind dirty hash:
```
"git:version": "set -o pipefail && (set -o pipefail && git tag --points-at HEAD | grep -oP '^v\\d+\\.\\d+\\.\\d+$' | tr -d 'v' | xargs echo -n) || (set -o pipefail && git rev-parse --short HEAD | xargs echo -n) && (git diff-index --quiet HEAD || (set -o pipefail && echo -n '-dirty-' && git diff | sha1sum | head -c 7))",
```

**Comment by tvdstaaij** [comment]
Hello, thank you for your interest in this module.

The purpose of this module is to provide the information that you would normally get from `git describe` using a JS API. I feel that adding information derived from other git inspection commands is beyond the intended scope. It would be better suited to a git diff module, git utilities module, or maybe even its own module.
