### ISSUE TITLE
When there is no tag in the repository, "+NaN" is returned

### ISSUE THREAD

**Issue by james-hu** [tvdstaaij/node-git-describe#2]
When there was no tag in the repository, I got "+NaN.74edeea.dirty" as the return value of: gitDescribe(undefined, {customArguments: ["--always"]}).semverString;

I guess it was caused by an invalid value of distance.

**Comment by tvdstaaij** [comment]
This was fixed together with #1, the code just didn't expect the output git gives with `--always` when there are no tags (i.e. just a commit hash). Wanted to make one little remark -- you can just pass in your config object as the first argument (`gitDescribe({customArguments: [...]})`), no need to explicitly skip it with null/undefined :wink:

**Comment by james-hu** [comment]
thanks for quick response and the hint!
